<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Production data-clean migration — Part 2.
 *
 * Removes ALL records from:
 *   • account_transfers    (inter-account moves — affected current_balance)
 *   • supplier_payments    (money out to suppliers — affected current_balance)
 *   • invoice_payments     (money in from clients — affected current_balance)
 *
 * Also removes the journal entries generated by those modules
 * (source_type IN 'payment', 'supplier_payment', 'account_transfer',
 *  'account_transfer_reversal') and their lines (cascade).
 *
 * Resets affected invoice state:
 *   • amount_paid → 0
 *   • status → 'sent'   for any invoice currently 'paid' or 'partially_paid'
 *
 * bank_accounts.current_balance was already zeroed by the previous migration
 * (2026_05_05_000002). It remains at 0 — correct for a full clean slate.
 *
 * Left untouched: invoices, purchase orders, COA, gensets, clients, suppliers,
 * users, fuel logs, maintenance records (and their own JEs).
 *
 * This migration is IRREVERSIBLE.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::transaction(function () {

            // ── Step 1: Clear reversed_by_id pointing INTO the JE set ───────
            // Prevents FK self-reference constraint issues during bulk delete.
            DB::statement("
                UPDATE journal_entries AS outer_je
                JOIN journal_entries AS target
                    ON outer_je.reversed_by_id = target.id
                   AND target.source_type IN (
                       'payment',
                       'supplier_payment',
                       'account_transfer',
                       'account_transfer_reversal'
                   )
                SET outer_je.reversed_by_id = NULL
            ");

            // Also null within the set itself
            DB::statement("
                UPDATE journal_entries
                SET reversed_by_id = NULL
                WHERE source_type IN (
                    'payment',
                    'supplier_payment',
                    'account_transfer',
                    'account_transfer_reversal'
                )
            ");

            // ── Step 2: Delete the journal entries (lines cascade) ───────────
            // nullOnDelete FKs triggered automatically:
            //   • account_transfers.journal_entry_id     → NULL
            //   • supplier_payments.journal_entry_id     → NULL
            //   • invoice_payments.journal_entry_id      → NULL
            DB::statement("
                DELETE FROM journal_entries
                WHERE source_type IN (
                    'payment',
                    'supplier_payment',
                    'account_transfer',
                    'account_transfer_reversal'
                )
            ");

            // ── Step 3: Delete account transfers ────────────────────────────
            // reversal_of_transfer_id is a plain unsignedBigInteger (no FK),
            // so no constraint to worry about.
            DB::statement("DELETE FROM account_transfers");

            // ── Step 4: Delete supplier payments ────────────────────────────
            DB::statement("DELETE FROM supplier_payments");

            // ── Step 5: Delete invoice payments ─────────────────────────────
            DB::statement("DELETE FROM invoice_payments");

            // ── Step 6: Reset invoice paid state ────────────────────────────
            // Invoices whose payments are gone must go back to 'sent' status
            // so they are visible as outstanding again.
            DB::statement("
                UPDATE invoices
                SET amount_paid = 0,
                    status = 'sent'
                WHERE status IN ('paid', 'partially_paid')
            ");
        });
    }

    public function down(): void
    {
        throw new \RuntimeException(
            'Migration 2026_05_05_000003_clean_transfers_supplier_payments_invoice_payments is irreversible.'
        );
    }
};
