<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Production data-clean migration.
 *
 * Removes ALL records from:
 *   • bank_statements   (cascades → bank_transactions)
 *   • expenses
 *   • cash_requests     (cascades → cash_request_items)
 *   • daily_closings    (daily cash-up snapshots)
 *
 * Also removes the journal entries that were generated by those modules
 * (source_type IN expense, cash_request, bank_statement) and their lines
 * (cascade).
 *
 * Resets bank_accounts.current_balance to 0 since every outflow entry
 * that contributed to those balances is being erased.
 *
 * SAFE ordering — no FK violations:
 *   1. Null self-referential reversed_by_id inside the JE set
 *   2. Delete those JEs  → lines cascade, nulls expense/cr/bt journal_entry_id
 *   3. Delete bank_statements → bank_transactions cascade
 *   4. Delete expenses        → nulls cash_requests.expense_id
 *   5. Delete cash_requests   → cash_request_items cascade
 *   6. Delete daily_closings
 *   7. Zero bank_account running balances
 *
 * This migration is IRREVERSIBLE — data cannot be recovered once run.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::transaction(function () {

            // ── Step 1: Clear self-referential FK inside the JE set ──────────
            // journal_entries.reversed_by_id is a nullable self-FK (nullOnDelete).
            // Nulling it first prevents any ordering issue in the bulk delete.
            DB::statement("
                UPDATE journal_entries
                SET reversed_by_id = NULL
                WHERE source_type IN ('expense', 'cash_request', 'bank_statement')
            ");

            // Also clear reversed_by_id that points INTO the set from outside
            // (e.g. a manual JE that reversed an expense JE).
            DB::statement("
                UPDATE journal_entries AS outer_je
                JOIN journal_entries AS target
                    ON outer_je.reversed_by_id = target.id
                   AND target.source_type IN ('expense', 'cash_request', 'bank_statement')
                SET outer_je.reversed_by_id = NULL
            ");

            // ── Step 2: Delete journal entries (lines cascade automatically) ─
            // nullOnDelete FKs triggered automatically:
            //   • expenses.journal_entry_id          → NULL
            //   • bank_transactions.journal_entry_id → NULL
            //   • cash_requests.journal_entry_id     → NULL
            //   • cash_requests.retire_journal_entry_id → NULL
            //   • maintenance_records.journal_entry_id  → NULL (only those that
            //     pointed to expense/cash_request JEs — maintenance's own JEs
            //     with source_type='maintenance' are left untouched)
            DB::statement("
                DELETE FROM journal_entries
                WHERE source_type IN ('expense', 'cash_request', 'bank_statement')
            ");

            // ── Step 3: Delete bank statements (bank_transactions cascade) ───
            DB::statement("DELETE FROM bank_statements");

            // ── Step 4: Delete expenses ──────────────────────────────────────
            // nullOnDelete FK triggers: cash_requests.expense_id → NULL
            DB::statement("DELETE FROM expenses");

            // ── Step 5: Delete cash requests (cash_request_items cascade) ────
            DB::statement("DELETE FROM cash_requests");

            // ── Step 6: Delete daily closing snapshots ───────────────────────
            DB::statement("DELETE FROM daily_closings");

            // ── Step 7: Reset bank account running balances ──────────────────
            // All outflow entries that contributed to these balances are gone.
            DB::statement("UPDATE bank_accounts SET current_balance = 0");
        });
    }

    public function down(): void
    {
        // Intentionally left empty — deleted data cannot be restored.
        throw new \RuntimeException(
            'Migration 2026_05_05_000002_clean_expenses_cash_requests_bank_statements is irreversible.'
        );
    }
};
